### PR TITLE
docker module does not have the state of running

### PR DESCRIPTION
**Pull request by huikang**

### CODE REVIEW

**Comment by defunctzombie** [comment]
But the goal is to specifically say it must also be running. Can you point to the docs for this? Maybe things have changed.

**Comment by huikang** [comment]
@defunctzombie 
This is the link 
http://docs.ansible.com/docker_module.html

If you look at the row of state in the table, there is not running. Thanks.

**Comment by defunctzombie** [comment]
We should use `started` here in that case.

**Comment by huikang** [comment]
cool. I have changed it to started

**Comment by defunctzombie** [comment]
please squash commits since first once is no longer needed

**Comment by huikang** [comment]
squashed. Please check it out. Thanks.

**Pull request merged**
